// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOhJA9el1TvgBWFssktZOMtJ-HPY9ksdQ',
    appId: '1:407168428738:web:0272ec20b6abc5c3bf695b',
    messagingSenderId: '407168428738',
    projectId: 'hema-63b81',
    authDomain: 'hema-63b81.firebaseapp.com',
    storageBucket: 'hema-63b81.firebasestorage.app',
    measurementId: 'G-QGJP8W0T5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApYkCz_c2ur_nDIY3naKltl70RCMhCCsk',
    appId: '1:407168428738:android:d75c470c15c9453dbf695b',
    messagingSenderId: '407168428738',
    projectId: 'hema-63b81',
    storageBucket: 'hema-63b81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6u-KX8qF5CIGOyWSIwX--rt-iivbQv0A',
    appId: '1:407168428738:ios:473072cbbb03c379bf695b',
    messagingSenderId: '407168428738',
    projectId: 'hema-63b81',
    storageBucket: 'hema-63b81.firebasestorage.app',
    iosClientId: '407168428738-769637fe8ff3v6o794lhv5pbb15fjivh.apps.googleusercontent.com',
    iosBundleId: 'com.calibreworks.hema',
  );

}